window.$$WDGET_RELATIONSHIP={
	"panel":[
		"grid":[
			"button",
			"label"
		],
		"form":[
			"textfield",
			"password",
			"datetimefield",
			"datefield"
		],
		"toolbar":[
			"button",
			"label"
		]
	]
}

window.$$WDGET_PARAME={
		"panel":{
			"attributes":{
				"region":{
					"description":"默认中间,如果设置布局方式为border,此属性表示布局方式的位置,有5个属性north上,west左,south下,center中间,east右边",
					"default":"center"
				},
				"layout":{
					"description":"当前组件下的子组件的布局方式",
					"default":"region",
				},
				"header":{
					"default":true,
					"description":"此属性有两个属性true和false,false表示隐藏标题,true表示显示标题"
				},
				"title":{
					"default":"",
					"description":"标题应该显示名称,默认为空"
				},
				"minWidth":{
					"default":120,
					"description":"当前面板的最小宽度"
				},
				"width":{
					"default":"100%",
					"description":"当前面板的宽度"
				},
				"collapsible":{
					"default":true,
					"description":"是否可以折叠true表示可以折叠,false表示无法进行折叠"
				}
			}
		},
		"grid":{
			"sqlid":{
				"default":"",
				"description":"在表单页面维护的sqlid"
			},
			"queryname":{
				"default":undefined,
				"description":"默认显示查询字段的字段名称"
			}
		},
		"form":{
			"layout":{
				"default":"form",
				"description":"显示的布局方式,默认为form表单布局方式"
			},
			"labelAlign":{
				"default":"right",
				"description":"标签的布局方式"
			},
			"columns":{
				"default":1,
				"description":"排列列的数量"
			}
		},
}